# Generated by Django 4.2.7 on 2026-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('portal', 'Portal User'), ('invoicing', 'Invoicing User')], default='portal', max_length=20),
        ),
    ]
