# Generated by Django 4.2.27 on 2026-01-31 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Business Owner)'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('invoicing', 'Invoicing User')], default='invoicing', max_length=20),
        ),
    ]
