# Generated by Django 4.2.27 on 2026-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_contact_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalaccount',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='autoanalyticalmodel',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags'),
        ),
    ]
