# Generated by Django 4.2.27 on 2026-02-01 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='budget_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='budget_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='budget_warning_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='budget_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='budget_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='budget_warning_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='budget_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='budget_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='budget_warning_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='budget_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='budget_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='budget_warning_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('check', 'Check'), ('online', 'Online Payment'), ('stripe', 'Stripe Payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('assets', 'Assets'), ('liabilities', 'Liabilities'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='transactions.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['account_code'],
            },
        ),
    ]
