# Generated by Django 4.2.27 on 2026-01-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetFieldExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetStageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color_code', models.CharField(default='#000000', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='stage',
            field=models.CharField(choices=[('planning', 'Planning'), ('approved', 'Approved'), ('active', 'Active'), ('monitoring', 'Monitoring'), ('closed', 'Closed')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
